kind: Deployment
apiVersion: apps/v1
metadata:
  name: backend-deployment
  namespace: wanderlust
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      name: backend
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: shadowigw/travel-backend:v2
          ports:
            - containerPort: 5173
            
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: wanderlust
spec:
  selector:
    app: backend
    ports:
      - port: 5173
        targetPort: 5173
        protocol: TCP
        nodePort: 31100


